---
title: ""
author: ""
date: ""
output: word_document
---

```{r setup, include=FALSE}
rm(list = ls())
library(lme4)
library(lmerTest)
library(car)
library(emmeans)
library(MuMIn)

source("/Users/chelseawilmer/Desktop/Github/Phenology/Phenology.data.cleanup.R")
str(pheno)

#make variables factors
pheno$Year <- as.factor(pheno$Year)
pheno$Site <- as.factor(pheno$Site)
pheno$PlotPair <- as.factor(pheno$PlotPair)
pheno$Plot_ID <- as.factor(pheno$Plot_ID)
pheno$Subplot_ID <- as.factor(pheno$Subplot_ID)
pheno$Treatment <- as.factor(pheno$Treatment)
pheno$Species <- as.factor(pheno$Species)
pheno$Functional.Type <- as.factor(pheno$Functional.Type)
pheno$Elevation <- as.integer(pheno$Elevation)

pheno$preNL <- pheno$NL - pheno$DOYsf
pheno$NL <- pheno$FLE - pheno$NL
pheno$FLE <- pheno$FOF - pheno$FLE
pheno$FOF <- pheno$FLCC - pheno$FOF
pheno$FLCC <- pheno$EOS - pheno$FLCC

#pheno <- filter(pheno, Site == "LM" | Site == "UM" | Site == "LSA" | Site == "USA")
```

**preNL ~ Site*Year*Treatment + Species + (1|PlotPair) + (1|Plot_ID) + (1|Subplot_ID), data = year)**
```{r, echo=FALSE}
model0 <- lmer(preNL ~ Site*Year*Treatment + Species + (1|PlotPair) + (1|Plot_ID) + (1|Subplot_ID), data = pheno)
anova(model0, ddf = "Kenward-Roger")

emmeans(model0, pairwise ~ Year|Site|Treatment)
emmeans(model0, pairwise ~ Treatment|Year|Site)
```

**NL ~ Site*Year*Treatment + Species + (1|PlotPair) + (1|Plot_ID) + (1|Subplot_ID), data = year)**
```{r, echo=FALSE}
model1 <- lmer(NL ~ Site*Year*Treatment + Species + (1|PlotPair) + (1|Plot_ID) + (1|Subplot_ID), data = pheno)
anova(model1, ddf = "Kenward-Roger")

emmeans(model1, pairwise ~ Year|Site|Treatment)
emmeans(model1, pairwise ~ Treatment|Year|Site)
```

**FLE ~ Site*Year*Treatment + Species + (1|PlotPair) + (1|Plot_ID) + (1|Subplot_ID), data = year)**
```{r, echo=FALSE}
model2 <- lmer(FLE ~ Site*Year*Treatment + Species + (1|PlotPair) + (1|Plot_ID) + (1|Subplot_ID), data = pheno)
anova(model2, ddf = "Kenward-Roger")

emmeans(model2, pairwise ~ Year|Site|Treatment)
emmeans(model2, pairwise ~ Treatment|Year|Site)
```

**FOF ~ Site*Year*Treatment + Species + (1|PlotPair) + (1|Plot_ID) + (1|Subplot_ID), data = year)**
```{r, echo=FALSE}
model3 <- lmer(FOF ~ Site*Year*Treatment + Species + (1|PlotPair) + (1|Plot_ID) + (1|Subplot_ID), data = pheno)
anova(model3, ddf = "Kenward-Roger")

emmeans(model3, pairwise ~ Year|Site|Treatment)
emmeans(model3, pairwise ~ Treatment|Year|Site)

```

**FLCC ~ Site*Year*Treatment + Species + (1|PlotPair) + (1|Plot_ID) + (1|Subplot_ID), data = year)**
```{r, echo=FALSE}
model4 <- lmer(FLCC ~ Site*Year*Treatment + Species + (1|PlotPair) + (1|Plot_ID) + (1|Subplot_ID), data = pheno)
anova(model4, ddf = "Kenward-Roger")

emmeans(model4, pairwise ~ Year|Site|Treatment)
emmeans(model4, pairwise ~ Treatment|Year|Site)

```

```{r, echo=FALSE}

```

```{r, echo=FALSE}

```

